# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_auth', '0002_pocketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketitem',
            name='downloaded_file',
            field=models.FileField(blank=None, default='', null=True, upload_to='pocket_items'),
        ),
    ]
